INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Kent Mackenzie'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Harry O. Hoyt'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jim Abrahams'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Edward F. Cline'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Brabin'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Stevens'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Delbert Mann'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Otto Preminger'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lewis Milestone'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ridley Scott'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jim Jarmusch'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rob Reiner'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Vincente Minnelli'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Tod Browning'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lynn Reynolds'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ivan Reitman'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Stevenson'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Arthur Rosson'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Ford'),(SELECT genre_id FROM genre WHERE genre_category = 'History'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Joseph Kane'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Melvin Frank'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Steven Spielberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Wise'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Powell'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Hughes'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Zemeckis'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'F.W. Murnau'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fred C. Newmeyer'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Aldrich'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sydney Pollack'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'King Vidor'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Roy Hill'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rex Ingram'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Spike Lee'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Ford'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rouben Mamoulian'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Stevens'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lloyd Bacon'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Wise'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Mulligan'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William A. Wellman'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred E. Green'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Martin Ritt'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Chaplin'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Clarence G. Badger'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Clarence G. Badger'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ridley Scott'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George A. Romero'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Delmer Daves'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Harold Ramis'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Cukor'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jerome Robbins'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Joseph L. Mankiewicz'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Lasseter'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Maurice Tourneur'),(SELECT genre_id FROM genre WHERE genre_category = 'Family'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'James Frawley'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Irving Rapper'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Barton'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Francis Ford Coppola'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Siodmak'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Woody Allen'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'James Whale'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Fitzmaurice'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Kevin Costner'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'F.W. Murnau'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Max Ophüls'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Dieterle'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William A. Wellman'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Worthington'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Roger Corman'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fred Niblo'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Rossen'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Henry Koster'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Swickard'),(SELECT genre_id FROM genre WHERE genre_category = 'Romance'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Douglas Sirk'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jim McBride'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Penny Marshall'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Lamont'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sidney Lumet'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mitchell Leisen'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Wayne Wang'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rupert Julian'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Steven Soderbergh'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mel Stuart'),(SELECT genre_id FROM genre WHERE genre_category = 'Family'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fred C. Newmeyer'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Gordon'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ida Lupino'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Milos Forman'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'T. Hayes Hunter'),(SELECT genre_id FROM genre WHERE genre_category = 'None'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Francis Ford Coppola'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rouben Mamoulian'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Louis Malle'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Capra'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Schlesinger'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Billy Woodberry'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jim Sharman'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fritz Lang'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Laughton'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William A. Wellman'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Franklin J. Schaffner'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Noel M. Smith'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Cecil B. DeMille'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Shirley Clarke'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'James Whale'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Raoul Walsh'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'David Anspaugh'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Seaton'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Wyler'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'D.W. Griffith'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Franklin J. Schaffner'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Cukor'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Roy Hill'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Emilio Fernández'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Thomas H. Ince'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Karl Freund'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Daniel Petrie'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Oscar Micheaux'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Richard Fleischer'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Hal Ashby'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Norbert A. Myles'),(SELECT genre_id FROM genre WHERE genre_category = 'Romance'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mel Brooks'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sidney Lumet'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Clint Eastwood'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stanton Kaye'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Henry King'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Haskell Wexler'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'James Cameron'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sidney Lumet'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stanley Kubrick'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Maurice Schwartz'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Harry dAbbadie dArrast'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Gregory La Cava'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Gordon Parks'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Wyler'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Howard Hawks'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Steven Spielberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Nathan Juran'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Dennis Hopper'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Altman'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Carroll Ballard'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Edward Sedgwick'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Cimino'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Pál Fejös'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ernst Lubitsch'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred Hitchcock'),(SELECT genre_id FROM genre WHERE genre_category = 'Mystery'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Arthur Penn'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Curtis Hanson'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Capra'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jules Dassin'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Clint Eastwood'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sergio Leone'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Julie Dash'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Irving Cummings'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Edgar G. Ulmer'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert J. Flaherty'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Curtiz'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Frankenheimer'),(SELECT genre_id FROM genre WHERE genre_category = 'Sci_Fi'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Leo McCarey'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Friedkin'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jack Arnold'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Don Siegel'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'David Lynch'),(SELECT genre_id FROM genre WHERE genre_category = 'Fantasy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stanley Kramer'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stanley Kubrick'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Clarence Brown'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Wes Anderson'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Abraham Polonsky'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Singleton'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Joseph H. Lewis'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Samuel Fuller'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Bob Rafelson'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Steven Spielberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Clarence Brown'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'King Vidor'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Rodriguez'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lilly Wachowski'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Gordon Parks'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Curtiz'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William A. Wellman'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Florey'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Preston Sturges'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Byron Haskin'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lowell Sherman'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William C. de Mille'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ramón Menéndez'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jonathan Demme'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Ford'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred Hitchcock'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred E. Green'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Joseph Santley'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John M. Stahl'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Capra'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Félix Padilla'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Karl Brown'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'W.S. Van Dyke'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Wyler'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John G. Avildsen'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Richard Linklater'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'David Butler'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Joan Micklin Silver'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Andrew L. Stone'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mike Nichols'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Cassavetes'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Robert Daly'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Terrence Malick'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Godfrey Reggio'),(SELECT genre_id FROM genre WHERE genre_category = 'Documentary'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Samuel Armstrong'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stanley Kubrick'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jacques Tourneur'),(SELECT genre_id FROM genre WHERE genre_category = 'Fantasy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rob Minkoff'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Tashlin'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Boorman'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Maurice Tourneur'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Philip Kaufman'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ivan Dixon'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Martin Scorsese'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Grace Cunard'),(SELECT genre_id FROM genre WHERE genre_category = 'Short'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Orson Welles'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Anthony Mann'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Burnett'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Irvin Kershner'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Christian Nyby'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Richard Rosson'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Kirk Wise'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Altman'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jerry Lewis'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Preston Sturges'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Albert Parker'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Martin Scorsese'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mervyn LeRoy'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ernest B. Schoedsack'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Tony Scott'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Gene Kelly'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'David Kirkland'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Josef von Sternberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ethan Coen'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'W.S. Van Dyke'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Howard Hawks'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred Hitchcock'),(SELECT genre_id FROM genre WHERE genre_category = 'Film_Noir'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Billy Wilder'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Richard Brooks'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George B. Seitz'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Steven Spielberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Melton Barker'),(SELECT genre_id FROM genre WHERE genre_category = 'Short'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Wyler'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Monte Hellman'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Victor Fleming'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Billy Wilder'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Josef von Sternberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Bob Fosse'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Raoul Walsh'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Howard Hawks'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Beaudine'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Raoul Walsh'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Spencer Williams'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lois Weber'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lewis H. Moomaw'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Marshall'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Herbert J. Biberman'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Ford'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rob Reiner'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Frankenheimer'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alan Crosland'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mervyn LeRoy'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mervyn LeRoy'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Lucas'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Huston'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ethan Coen'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Leo McCarey'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Efrain Gutierrez'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jack Conway'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Edwin S. Porter'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lewis Milestone'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William A. Seiter'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'André De Toth'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sidney Olcott'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Melford'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Borzage'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Orson Welles'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Spike Lee'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Henry King'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Stevens'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fred M. Wilcox'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred Hitchcock'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Curtiz'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Blake Edwards'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Clouse'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Reginald Barker'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Lloyd Bacon'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Phillips Smalley'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Budd Boetticher'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Cecil B. DeMille'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Morris Engel'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Herbert Brenon'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'W.S. Van Dyke'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Nicholas Ray'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Norman Jewison'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Carpenter'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Edward S. Curtis'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Frank Darabont'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fred Zinnemann'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Reginald Barker'),(SELECT genre_id FROM genre WHERE genre_category = 'Western'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Roman Polanski'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Sturges'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Friedkin'),(SELECT genre_id FROM genre WHERE genre_category = 'Horror'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Victor Sjöström'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'James Whale'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Dorothy Arzner'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Lucas'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mervyn LeRoy'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Roemer'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Chaplin'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Ford'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mike Nichols'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Elia Kazan'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stuart Rosenberg'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sam Wood'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Peter Bogdanovich'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alexander Hall'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Badham'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rouben Mamoulian'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Terrence Malick'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ridley Scott'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Bob Clark'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'David Lean'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Fred Zinnemann'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sam Wood'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Howard Hawks'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alexander Mackendrick'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alfred Hitchcock'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Vincente Minnelli'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William C. de Mille'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Amy Heckerling'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Billy Wilder'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Jacques Tourneur'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Zemeckis'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Walters'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Stanley Donen'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Norman Z. McLeod'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Arthur Penn'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Elia Kazan'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Buster Keaton'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sam Peckinpah'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Michael Curtiz'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William Cottrell'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Alan J. Pakula'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Sayles'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Reisner'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Edmund Goulding'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Landis'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Gregory Nava'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Sam Peckinpah'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Richard Thorpe'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Peter Yates'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Boorman'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Elia Kazan'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Don Siegel'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Huston'),(SELECT genre_id FROM genre WHERE genre_category = 'Adventure'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Mark Sandrich'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Bryant'),(SELECT genre_id FROM genre WHERE genre_category = 'Biography'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Arthur Hiller'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Emerson'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Charles Vidor'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Richard Brooks'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Robert Downey Sr.'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Ben Sharpsteen'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'William K. Howard'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Quentin Tarantino'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Morton DaCosta'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Anthony Mann'),(SELECT genre_id FROM genre WHERE genre_category = 'Action'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Erich von Stroheim'),(SELECT genre_id FROM genre WHERE genre_category = 'Drama'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Busby Berkeley'),(SELECT genre_id FROM genre WHERE genre_category = 'Music'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'Rudolph Maté'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'John Murray Anderson'),(SELECT genre_id FROM genre WHERE genre_category = 'Animation'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Marshall'),(SELECT genre_id FROM genre WHERE genre_category = 'Comedy'));
INSERT INTO movies.bridge(director_id, genre_id) VALUES ((SELECT director_id FROM director where director_name = 'George Loane Tucker'),(SELECT genre_id FROM genre WHERE genre_category = 'Crime'));
